import type { Cover, CoverId, CoverLocale } from '../types';
import { locale } from '../i18n';
import manifest from '../data/covers.manifest.json';

// All covers live in covers.manifest.json — both the seed lineup AND any
// future issues generated by the cron at .github/workflows/auto-cover.yml.
// One source of truth means the cron can append to JSON without touching
// any TypeScript, and the runtime always picks up the new issue on the
// next build (the cron pushes a fresh deploy each drop).
//
// Cadence: one new cover every 2 days, dropping at 00:00 UTC. The cron
// computes the next releasedOn as `max(existing.releasedOn) + 2 days`.
export const COVERS: Cover[] = manifest as Cover[];

/** Look up a cover by id. Returns null when unknown (covers can be retired). */
export function findCover(id: CoverId): Cover | null {
  return COVERS.find(c => c.id === id) ?? null;
}

/** Look up a cover by id. Throws when unknown — for paths that own the id. */
export function getCover(id: CoverId): Cover {
  const c = findCover(id);
  if (!c) throw new Error(`unknown cover: ${id}`);
  return c;
}

/**
 * The newsstand rack. Covers whose releasedOn is in the past, newest first.
 * `now` is injectable so tests / the newsstand re-render path can pass a
 * stable value, but defaults to the wall-clock instant.
 */
export function liveCovers(now: number = Date.now()): Cover[] {
  return COVERS
    .filter(c => Date.parse(c.releasedOn) <= now)
    .sort((a, b) => Date.parse(b.releasedOn) - Date.parse(a.releasedOn));
}

/**
 * The single sealed preview cover that drops next. Returns null when the
 * queue is empty — in that case the newsstand should not render a preview
 * slot or countdown (and the cron is overdue / failing).
 */
export function upcomingCover(now: number = Date.now()): Cover | null {
  const future = COVERS
    .filter(c => Date.parse(c.releasedOn) > now)
    .sort((a, b) => Date.parse(a.releasedOn) - Date.parse(b.releasedOn));
  return future[0] ?? null;
}

/** Look up a localized field, falling back to English. */
export function coverText(
  cover: Cover,
  field: 'title' | 'subtitle' | 'hook',
  lc?: CoverLocale,
): string {
  const l = (lc ?? locale()) as CoverLocale;
  const dict = cover[field];
  return dict[l] || dict.en;
}
